In [47]:
import numpy as np
import pandas as pd

In [48]:
ds=pd.read_csv('House Price Prediction Dataset.csv')

In [49]:
ds.head()

Id  Area  Bedrooms  Bathrooms  Floors  YearBuilt  Location  Condition  \
0   1  1360         5          4       3       1970  Downtown  Excellent   
1   2  4272         5          4       3       1958  Downtown  Excellent   
2   3  3592         2          2       3       1938  Downtown       Good   
3   4   966         4          2       2       1902  Suburban       Fair   
4   5  4926         1          4       2       1975  Downtown       Fair   

  Garage   Price  
0     No  149919  
1     No  424998  
2     No  266746  
3    Yes  244020  
4    Yes  636056

In [72]:
l_unique=ds['Location'].unique()
c_unique=ds['Condition'].unique()
g_unique=ds['Garage'].unique()
#for i,j in zip(l_unique , c_unique):
   #print("Unique Location = " , i)
   #print("Unique Condition = ",j)
print("Unique Locations = " , l_unique)
print("Unique Conditions =" , c_unique)
print("Unique Garage =" , g_unique)

Unique Locations =  ['Downtown' 'Suburban' 'Urban' 'Rural']
Unique Conditions = ['Excellent' 'Good' 'Fair' 'Poor']
Unique Garage = ['No' 'Yes']


In [100]:
ds_dummies=pd.get_dummies(ds, columns=['Location' , 'Condition', 'Garage'] , dtype=int) # generate dummies
dummy_columns = ds_dummies.columns.difference(ds.columns) # to get dummy columns data
ds_dummies[dummy_columns] # print dummy column data

Condition_Excellent  Condition_Fair  Condition_Good  Condition_Poor  \
0                       1               0               0               0   
1                       1               0               0               0   
2                       0               0               1               0   
3                       0               1               0               0   
4                       0               1               0               0   
...                   ...             ...             ...             ...   
1995                    0               0               0               1   
1996                    0               0               0               1   
1997                    0               0               0               1   
1998                    1               0               0               0   
1999                    0               1               0               0   

      Garage_No  Garage_Yes  Location_Downtown  Location_Rural  \
0             1           0                  1               0   
1             1           0                  1               0   
2             1           0                  1               0   
3             0           1                  0               0   
4             0           1                  1               0   
...         ...         ...                ...             ...   
1995          1           0                  0               0   
1996          0           1                  0               0   
1997          1           0                  0               1   
1998          0           1                  0               0   
1999          1           0                  0               0   

      Location_Suburban  Location_Urban  
0                     0               0  
1                     0               0  
2                     0               0  
3                     1               0  
4                     0               0  
...                 ...             ...  
1995                  1               0  
1996                  1               0  
1997                  0               0  
1998                  0               1  
1999                  1               0  

[2000 rows x 10 columns]

In [104]:
merge_dummy_dataset=pd.concat([ds,ds_dummies[dummy_columns]] , axis='columns')
merge_dummy_dataset

Id  Area  Bedrooms  Bathrooms  Floors  YearBuilt  Location  Condition  \
0        1  1360         5          4       3       1970  Downtown  Excellent   
1        2  4272         5          4       3       1958  Downtown  Excellent   
2        3  3592         2          2       3       1938  Downtown       Good   
3        4   966         4          2       2       1902  Suburban       Fair   
4        5  4926         1          4       2       1975  Downtown       Fair   
...    ...   ...       ...        ...     ...        ...       ...        ...   
1995  1996  4994         5          4       3       1923  Suburban       Poor   
1996  1997  3046         5          2       1       2019  Suburban       Poor   
1997  1998  1062         5          1       2       1903     Rural       Poor   
1998  1999  4062         3          1       2       1936     Urban  Excellent   
1999  2000  2989         5          1       3       1903  Suburban       Fair   

     Garage   Price  Condition_Excellent  Condition_Fair  Condition_Good  \
0        No  149919                    1               0               0   
1        No  424998                    1               0               0   
2        No  266746                    0               0               1   
3       Yes  244020                    0               1               0   
4       Yes  636056                    0               1               0   
...     ...     ...                  ...             ...             ...   
1995     No  295620                    0               0               0   
1996    Yes  580929                    0               0               0   
1997     No  476925                    0               0               0   
1998    Yes  161119                    1               0               0   
1999     No  482525                    0               1               0   

      Condition_Poor  Garage_No  Garage_Yes  Location_Downtown  \
0                  0          1           0                  1   
1                  0          1           0                  1   
2                  0          1           0                  1   
3                  0          0           1                  0   
4                  0          0           1                  1   
...              ...        ...         ...                ...   
1995               1          1           0                  0   
1996               1          0           1                  0   
1997               1          1           0                  0   
1998               0          0           1                  0   
1999               0          1           0                  0   

      Location_Rural  Location_Suburban  Location_Urban  
0                  0                  0               0  
1                  0                  0               0  
2                  0                  0               0  
3                  0                  1               0  
4                  0                  0               0  
...              ...                ...             ...  
1995               0                  1               0  
1996               0                  1               0  
1997               1                  0               0  
1998               0                  0               1  
1999               0                  1               0  

[2000 rows x 20 columns]

In [105]:
drop_location=merge_dummy_dataset.drop(['Location' , 'Location_Downtown' ,'Condition' , 'Garage' , 'Condition_Excellent' , 'Garage_No'] , axis='columns')
drop_location

Id  Area  Bedrooms  Bathrooms  Floors  YearBuilt   Price  \
0        1  1360         5          4       3       1970  149919   
1        2  4272         5          4       3       1958  424998   
2        3  3592         2          2       3       1938  266746   
3        4   966         4          2       2       1902  244020   
4        5  4926         1          4       2       1975  636056   
...    ...   ...       ...        ...     ...        ...     ...   
1995  1996  4994         5          4       3       1923  295620   
1996  1997  3046         5          2       1       2019  580929   
1997  1998  1062         5          1       2       1903  476925   
1998  1999  4062         3          1       2       1936  161119   
1999  2000  2989         5          1       3       1903  482525   

      Condition_Fair  Condition_Good  Condition_Poor  Garage_Yes  \
0                  0               0               0           0   
1                  0               0               0           0   
2                  0               1               0           0   
3                  1               0               0           1   
4                  1               0               0           1   
...              ...             ...             ...         ...   
1995               0               0               1           0   
1996               0               0               1           1   
1997               0               0               1           0   
1998               0               0               0           1   
1999               1               0               0           0   

      Location_Rural  Location_Suburban  Location_Urban  
0                  0                  0               0  
1                  0                  0               0  
2                  0                  0               0  
3                  0                  1               0  
4                  0                  0               0  
...              ...                ...             ...  
1995               0                  1               0  
1996               0                  1               0  
1997               1                  0               0  
1998               0                  0               1  
1999               0                  1               0  

[2000 rows x 14 columns]

In [106]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [107]:
x=drop_location.drop(['Price'] , axis='columns')
x

Id  Area  Bedrooms  Bathrooms  Floors  YearBuilt  Condition_Fair  \
0        1  1360         5          4       3       1970               0   
1        2  4272         5          4       3       1958               0   
2        3  3592         2          2       3       1938               0   
3        4   966         4          2       2       1902               1   
4        5  4926         1          4       2       1975               1   
...    ...   ...       ...        ...     ...        ...             ...   
1995  1996  4994         5          4       3       1923               0   
1996  1997  3046         5          2       1       2019               0   
1997  1998  1062         5          1       2       1903               0   
1998  1999  4062         3          1       2       1936               0   
1999  2000  2989         5          1       3       1903               1   

      Condition_Good  Condition_Poor  Garage_Yes  Location_Rural  \
0                  0               0           0               0   
1                  0               0           0               0   
2                  1               0           0               0   
3                  0               0           1               0   
4                  0               0           1               0   
...              ...             ...         ...             ...   
1995               0               1           0               0   
1996               0               1           1               0   
1997               0               1           0               1   
1998               0               0           1               0   
1999               0               0           0               0   

      Location_Suburban  Location_Urban  
0                     0               0  
1                     0               0  
2                     0               0  
3                     1               0  
4                     0               0  
...                 ...             ...  
1995                  1               0  
1996                  1               0  
1997                  0               0  
1998                  0               1  
1999                  1               0  

[2000 rows x 13 columns]

In [108]:
y=drop_location['Price']
y

0       149919
1       424998
2       266746
3       244020
4       636056
         ...  
1995    295620
1996    580929
1997    476925
1998    161119
1999    482525
Name: Price, Length: 2000, dtype: int64

In [109]:
model.fit(x,y)

LinearRegression()

In [111]:
model.predict([[1990,2800,3,2,3,2000,0,1,0,0,1,0,0]])

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([541723.11801608])

In [114]:
model.predict([[2024,5000,5,5,2,2025,1,1,1,1,1,1,1]])

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([539693.30373844])

In [115]:
model.predict([[1,35670,4,8,3,2025,0,0,0,0,0,0,0]])

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([541989.77447249])